// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewSeleneseIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new ChromeDriver();
    //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void sampleapp2() {
    //System.setProperty("webdriver.chrome.driver","C:\\Users\\rbanas2\\Downloads\\chromedriver80\\chromedriver.exe");
    System.setProperty("webdriver.chrome.driver","C:\\Program Files (x86)\\Jenkins\\workspace\\chromedriver.exe");
    WebDriver driver = new ChromeDriver();
    driver.get("https://h5qts1hwccaarrahapcloud-approuter.cfapps.eu10.hana.ondemand.com/SAPCloudSAPCloud-1.0.0/index.html");
    /*driver.manage().window().setSize(new Dimension(1478, 824));
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).click();
    {
      WebElement element = driver.findElement(By.id("j_username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("j_username")).sendKeys("chelabasolo03@gmail.com");
    driver.findElement(By.id("j_password")).sendKeys("sp0617Chel");
    driver.findElement(By.id("logOnFormSubmit")).click();*/
    
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("chelabasolo03@gmail.com");
    driver.findElement(By.name("password")).sendKeys("sp0617Chel");
    driver.findElement(By.cssSelector(".island")).click();
    driver.findElement(By.cssSelector(".island-button")).click();
    //driver.findElement(By.id("__xmlview0--btnDisplay")).click();
    //driver.findElement(By.id("__xmlview0--btnClear")).click();
    //driver.findElement(By.id("__xmlview0--btnDisplay")).click();
    //driver.findElement(By.id("__xmlview0--btnClear")).click();
    
    System.out.println("TEST COMPLETED.");

    //driver.close();
    
    //driver.quit();
  }
}
